version: 2
jobs:
  build:
    docker:
      - image: karlrun/java-node-gradle:latest
    steps:
      - checkout
      - run: ./gradlew assemble
  test:
    docker:
      - image: karlrun/java-node-gradle:latest
    steps:
      - run: ./gradlew check