version: 2
jobs:
  build:
    docker:
      - image: gradle:jdk8-alpine
      - image: node:current-slim
    steps:
      - checkout
      - run: ./gradlew assemble
  test:
    docker:
      - image: karlrun/java-node-gradle:latest
    steps:
      - checkout
      - run: ./gradlew check
  deploy:
    docker:
      - image: karlrun/java-node-gradle:latest
    steps:
      - run: echo "hello from deploy"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy