version: 2
jobs:
  build:
    docker:
      - image: karlrun/java-node-gradle:latest
    steps:
      - checkout
      - run: ./gradlew assemble
  test:
    docker:
      - image: karlrun/java-node-gradle:latest
    steps:
      - checkout
      - run: ./gradlew check
  deploy:
    docker:
      - image: gradle:alpine
    steps:
      - checkout
      - run:
          name: Deploy Master to CloudFoundry
          command: |
            ./gradlew cfPush -PcfUsername=$CFUSER -PcfPassword=$CFPASS

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test