version: 2
jobs:
  build:
    docker:
      - image: karlrun/java-node-gradle:latest
    steps:
      - checkout
      - run: ./gradlew assemble
  test:
    docker:
      - image: karlrun/java-node-gradle:latest
    steps:
      - run: ./gradlew check
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test